### PR TITLE
remapped pgex to new location

### PR DESCRIPTION
**Pull request by oddbookworm**

### CODE REVIEW

**Review by SSS-Says-Snek — CHANGES_REQUESTED** [review]
There's a typo (pygame_exampless)

**Review by SSS-Says-Snek — APPROVED** [review]
LGTM!

**Review by Matiiss — COMMENTED** [review]
Maybe it should link directly to the actual examples directory: https://github.com/pygame-examples/pygame_examples/tree/main/pgex/examples

**Review by Matiiss — APPROVED** [review]
LGTM

**Review by SSS-Says-Snek — DISMISSED** [review]
Test

**Review by Matiiss — COMMENTED** [review]
**Comment**
Submit general feedback without explicit approval.

**Review by SSS-Says-Snek — DISMISSED** [review]
Test review uno

**Review by Matiiss — APPROVED** [review]
test review 2: electric boogaloo

**Review by SSS-Says-Snek — COMMENTED** [review]
Comment

**Review by SSS-Says-Snek — APPROVED** [review]
Yo

**Pull request merged**
